language: android # lol
jdk: oraclejdk8
sudo: true

android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.2
    - android-28

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
  - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
  - wget -O - https://github.com/jphp-compiler/jphp/releases/download/jppm-0.3.8/jppm-setup-0.3.8.sh | sudo bash

script:
    - jppm version
    - cd jphp-android-ext && jppm publish --yes && cd ..
    - cd jppm-android-plugin && jppm publish --yes cd ..
    - cd ./sandbox/
    - jppm update
    - jppm android:apk
